learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from . import views


app_name = 'learning_logs'

urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем.
    path('topics/', views.Topics.as_view(), name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Страница для чтения записи
    path('read_entry/<int:entry_id>/', views.read_entry, name='read_entry'),
    # Страница для удаления записи
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    # Страница для редактирования темы
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    # Страница для удаления темы
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
    # Страница для поиска темы по названию
    path('search_entries/', views.SearchEntries.as_view(), name='search_entries'),
    path('search_topics/', views.SearchTopics.as_view(), name='search_topics'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include
from . import views


app_name = 'users'

urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.


class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField("Title", max_length=200)
    image = models.ImageField("Image", upload_to="images_topics/", default='default.png')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="Date")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

    def get_delete_url(self):
        return reverse('learning_logs:delete_topic', kwargs={'topic_id': self.id})


class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name="Topic")
    image = models.ImageField("Image", upload_to="images_entries/", default='default.png')
    text = models.TextField(verbose_name="Content")
    date_added = models.DateTimeField(auto_now_add=True, verbose_name="Date")

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        if len(self.text) <= 100:
            return self.text
        return f"{self.text[:100]}..."

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'image']
        labels = {'text': '', 'image': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'image']
        labels = {'text': '', 'image': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404


# Create your views here.


def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'learning_logs/index.html')


class Topics(LoginRequiredMixin, ListView):
    template_name = 'learning_logs/topics.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.filter(owner=self.request.user).order_by('date_added')


@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    check_topic_owner(request, topic)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:read_entry', entry_id=entry_id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def read_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    context = {'entry': entry}
    return render(request, 'learning_logs/entry.html', context)


def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404


@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    check_topic_owner(request, entry.topic)
    entry.delete()
    return redirect('learning_logs:topic', topic_id=entry.topic.id)


@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    topic.delete()
    return redirect('learning_logs:topics')


@login_required
def edit_topic(request, topic_id):
    """Редактирует существующую тему."""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = TopicForm(instance=topic)
    else:
        # Отправка данных POST; обработать данные.
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


class Search(LoginRequiredMixin, ListView):

    def get_queryset(self):
        if self.request.GET.get('obj') == 'topic':
            self.template_name = 'learning_logs/topics.html'
            self.context_object_name = 'topics'
            return Topic.objects.filter(Q(text__icontains=self.request.GET.get("q")) & Q(owner=self.request.user))
        elif self.request.GET.get('obj') == 'entry':
            self.template_name = 'learning_logs/topic.html'
            self.context_object_name = 'entries'
            return Entry.objects.filter(Q(text__icontains=self.request.GET.get("q")) &
                                        Q(topic__id=self.request.GET.get("topic_id")))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        if self.request.GET.get('obj') == 'entry':
            context["topic"] = get_object_or_404(Topic, pk=self.request.GET.get("topic_id"))
        return context


class SearchTopics(LoginRequiredMixin, ListView):
    template_name = 'learning_logs/topics.html'
    context_object_name = 'topics'

    def get_queryset(self):
        return Topic.objects.filter(Q(text__icontains=self.request.GET.get("q")) & Q(owner=self.request.user))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        return context


class SearchEntries(LoginRequiredMixin, ListView):
    template_name = 'learning_logs/topic.html'
    context_object_name = 'entries'

    def get_queryset(self):
        return Entry.objects.filter(Q(text__icontains=self.request.GET.get("q")) &
                                    Q(topic__id=self.request.GET.get("topic_id")))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        return context

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'learning_logs/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'learning_logs/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 pt-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

    <script src="{% static 'learning_logs/js/search.js' %}"></script>
    <script src="{% static 'learning_logs/js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'learning_logs/js/fancybox.js' %}"></script>

    {% block script %}{% endblock script %}

</body>
</html>

learning_logs/templates/learning_logs/delete_message_window.html
<div style="display: none;" id="delete_message_window">
    <h4 class="text-center mb-4">Вы действительно хотите удалить <span id="title"></span>?</h4>
    <div class="d-flex justify-content-center">
        <a id="submit_btn" type="submit" class="btn btn-danger mr-3">Да</a>
        <button id="close_delete_message" class="btn btn-success">Нет</button>
    </div>
</div>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit entry:</h2>
{% endblock page_header %}

{% block content %}
    <h4 class="mb-4">
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h4>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit topic:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:edit_topic' topic.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/entry.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="d-flex justify-content-between align-content-center">
        <h3>{{ entry.topic }}</h3>
        <h3>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}"
                           class="btn btn-warning">edit entry</a>
        </h3>
    </div>
{% endblock page_header %}


{% block content %}

        <!--<img src="{{ entry.image.url }}" class="float-left mb-4 mw-100">
        <div class="float-left">
            {{ entry.text|linebreaks }}
        </div>-->
        <p>
            <img src="{{ entry.image.url }}" width="300" class="float-left mr-4 mb-4 col-md-4">
            {{ entry.text|linebreaks }}
        </p>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class='jumbotron'>
        <h1 class="display-3">Track your learning.</h1>
        <p class="lead">Make your own Learning Log, and keep a list of the
            topics you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
           role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new entry:</h2>
{% endblock page_header %}

{% block content %}
    <h4 class="mb-4">
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h4>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new topic:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="d-flex justify-content-between align-items-center flex-wrap">
        <h3>{{ topic }}</h3>
        <div id="search">
            <form action="{% url 'learning_logs:search_entries' %}">
                <input type="text" name="q" placeholder="Search entry..." class="form-control">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
            </form>
        </div>
        <a href="{% url 'learning_logs:new_entry' topic.id %}"
           class="btn btn-success">Add new entry</a>
    </div>
{% endblock page_header %}


{% block content %}
    <div class="d-flex flex-wrap justify-content-around pt-4">
        {% for entry in entries %}
            <div class="card mb-3">
                <div class="card-header d-flex justify-content-between align-content-center">
                    <h4>{{ entry.date_added|date:'M d, Y H:i' }}</h4>

                    <div>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}"
                           class="btn btn-warning"><i class="fa fa-pencil-square-o"></i></a>

                        <a href="javascript:;" data-deletelink
                           data-id="{{ entry.id }}"
                           data-text="пост {{ entry.text }}"
                           data-url="{% url 'learning_logs:delete_entry' entry.id  %}"
                           data-src="#delete_message_window"
                           class="btn btn-danger"><i class="fa fa-trash"></i></a>
                    </div>
                </div>
                <img src="{{ entry.image.url }}" class="img-fluid">
                <div class="card-body">
                    {{ entry|linebreaks }}
                </div>
                <a href="{% url 'learning_logs:read_entry' entry.id %}"
                           class="btn btn-success mx-4 mb-4">read</a>
            </div>
        {% empty %}
            <p>There are no entries for this topic yet.</p>
        {% endfor %}
    </div>

    {% include "learning_logs/delete_message_window.html" %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block page_header %}
    <div class="d-flex justify-content-between align-items-center flex-wrap">
        <h1>Topics</h1>
        <div id="search">
            <form action="{% url 'learning_logs:search_topics' %}">
                <input type="text" name="q" placeholder="Search topic..." class="form-control"
                value="{% if q %}{{ q }}{% endif %}">
            </form>
        </div>
        <a href="{% url 'learning_logs:new_topic' %}"
           class="btn btn-success">Add new topic</a>
    </div>
{% endblock page_header %}

{% block content %}
    <div class="d-flex flex-wrap justify-content-center pt-4">
        {% for topic in topics %}
            <a href="{% url 'learning_logs:topic' topic.id %}">
                <div class="card m-4">
                    <img class="card-img-top img-fluid"
                         src="{{ topic.image.url }}" alt="{{ topic }}">
                    <div class="card-body">
                        <h3 class="text-center">{{ topic }}</h3>
                    </div>
                    <a href="{% url 'learning_logs:edit_topic' topic.id %}"
                       class="btn btn-warning btn-edit"><i class="fa fa-pencil-square-o"></i></a>
                    <a href="javascript:;" data-deletelink
                       data-id="{{ topic.id }}"
                       data-text="тему {{ topic.text }}"
                       data-url="{% url 'learning_logs:delete_topic' topic.id  %}"
                       data-src="#delete_message_window"
                       class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></a>
                </div>
            </a>
        {% empty %}
            <h3 class="text-center">No topics have been added yet.</h3>
        {% endfor %}
    </div>

    {% include "learning_logs/delete_message_window.html" %}

{% endblock content %}


{% block script %}
    <script src="{% static 'learning_logs/js/search.js' %}"></script>
{% endblock script %}